### ISSUE TITLE
拖拽导致排序事件错误触发

### ISSUE THREAD

**Issue by yushungong** [surely-vue/table#73]
当同时开启排序和列宽拖拽时，当鼠标不是正好在列的右侧边缘线触发拖拽，而是在右侧边缘线偏左一点点触发拖拽时，并且向左拖拽，拖拽时会触发排序事件
![image](https://user-images.githubusercontent.com/82556554/184054290-e9ce2914-543a-4f13-bf0f-747ef88e8100.png)

**Comment by yushungong** [comment]
https://codesandbox.io/s/awesome-elion-mkkylg?file=/src/App.vue

**Comment by tangjinzhou** [comment]
先添加如下全局样式
```css
.surely-table-resize-handle.dragging::before {
    position: absolute;
    top: 0;
    bottom: 0;
    width: 100%;
    content: " ";
    width: 200vw;
    transform: translate(-50%);
    opacity: 0;
}
```
