### ISSUE TITLE
展开图标不垂直居中问题

### ISSUE THREAD

**Issue by yushungong** [surely-vue/table#78]
当table有可展开数据时，自定义 bodyCell 内容设置了一个高度后，展开图标不垂直居中
示例：https://codesandbox.io/s/awesome-elion-mkkylg?file=/src/App.vue:129-137

**Comment by tangjinzhou** [comment]
对于展开图标单独占一个单元格的时候会自动垂直居中，如果是和其他内容在一个单元格里，不会自动处理，毕竟有的人是不需要居中的，你可以添加如下样式让其居中

```css
.surely-table-cell-inner .surely-table-cell-content {
    display: flex;
    align-items: center;
}
```
